export type Language = { code: string; name: string; native: string; flag: string; rtl: boolean };

export const LANGUAGES: Language[] = [
  { code: "af", name: "Afrikaans", native: "Afrikaans", flag: "🇿🇦", rtl: false },
  { code: "sq", name: "Albanian", native: "Shqip", flag: "🇦🇱", rtl: false },
  { code: "am", name: "Amharic", native: "አማርኛ", flag: "🇪🇹", rtl: false },
  { code: "ar", name: "Arabic", native: "العربية", flag: "🇸🇦", rtl: true },
  { code: "hy", name: "Armenian", native: "Հայերեն", flag: "🇦🇲", rtl: false },
  { code: "as", name: "Assamese", native: "অসমীয়া", flag: "🇮🇳", rtl: false },
  { code: "az", name: "Azerbaijani", native: "Azərbaycan", flag: "🇦🇿", rtl: false },
  { code: "bm", name: "Bambara", native: "Bamanakan", flag: "🇲🇱", rtl: false },
  { code: "eu", name: "Basque", native: "Euskara", flag: "🇪🇸", rtl: false },
  { code: "be", name: "Belarusian", native: "Беларуская", flag: "🇧🇾", rtl: false },
  { code: "bn", name: "Bangla", native: "বাংলা", flag: "🇧🇩", rtl: false },
  { code: "bs", name: "Bosnian", native: "Bosanski", flag: "🇧🇦", rtl: false },
  { code: "bg", name: "Bulgarian", native: "Български", flag: "🇧🇬", rtl: false },
  { code: "my", name: "Burmese", native: "မြန်မာ", flag: "🇲🇲", rtl: false },
  { code: "ca", name: "Catalan", native: "Català", flag: "🇪🇸", rtl: false },
  { code: "ceb", name: "Cebuano", native: "Cebuano", flag: "🇵🇭", rtl: false },
  { code: "ny", name: "Nyanja", native: "Nyanja", flag: "🇲🇼", rtl: false },
  { code: "zh", name: "Chinese", native: "中文", flag: "🇨🇳", rtl: false },
  { code: "zh-TW", name: "Chinese (Taiwan)", native: "中文（台灣）", flag: "🇹🇼", rtl: false },
  { code: "co", name: "Corsican", native: "Corsican", flag: "🇫🇷", rtl: false },
  { code: "hr", name: "Croatian", native: "Hrvatski", flag: "🇭🇷", rtl: false },
  { code: "cs", name: "Czech", native: "Čeština", flag: "🇨🇿", rtl: false },
  { code: "da", name: "Danish", native: "Dansk", flag: "🇩🇰", rtl: false },
  { code: "dv", name: "Divehi", native: "Divehi", flag: "🇲🇻", rtl: true },
  { code: "nl", name: "Dutch", native: "Nederlands", flag: "🇳🇱", rtl: false },
  { code: "en", name: "English", native: "English", flag: "🇺🇸", rtl: false },
  { code: "en-GB", name: "British English", native: "British English", flag: "🇬🇧", rtl: false },
  { code: "eo", name: "Esperanto", native: "Esperanto", flag: "🌐", rtl: false },
  { code: "et", name: "Estonian", native: "Eesti", flag: "🇪🇪", rtl: false },
  { code: "ee", name: "Ewe", native: "Eʋegbe", flag: "🇬🇭", rtl: false },
  { code: "fil", name: "Filipino", native: "Filipino", flag: "🇵🇭", rtl: false },
  { code: "fi", name: "Finnish", native: "Suomi", flag: "🇫🇮", rtl: false },
  { code: "fr", name: "French", native: "Français", flag: "🇫🇷", rtl: false },
  { code: "fr-CA", name: "Canadian French", native: "Français canadien", flag: "🇨🇦", rtl: false },
  { code: "fy", name: "Western Frisian", native: "Frysk", flag: "🇳🇱", rtl: false },
  { code: "gl", name: "Galician", native: "Galego", flag: "🇪🇸", rtl: false },
  { code: "ka", name: "Georgian", native: "Ქართული", flag: "🇬🇪", rtl: false },
  { code: "de", name: "German", native: "Deutsch", flag: "🇩🇪", rtl: false },
  { code: "de-AT", name: "Austrian German", native: "Österreichisches Deutsch", flag: "🇦🇹", rtl: false },
  { code: "el", name: "Greek", native: "Ελληνικά", flag: "🇬🇷", rtl: false },
  { code: "gn", name: "Guarani", native: "Guarani", flag: "🇵🇾", rtl: false },
  { code: "gu", name: "Gujarati", native: "ગુજરાતી", flag: "🇮🇳", rtl: false },
  { code: "ht", name: "Haitian Creole", native: "Haitian Creole", flag: "🇭🇹", rtl: false },
  { code: "ha", name: "Hausa", native: "Hausa", flag: "🇳🇬", rtl: false },
  { code: "haw", name: "Hawaiian", native: "ʻŌlelo Hawaiʻi", flag: "🇺🇸", rtl: false },
  { code: "he", name: "Hebrew", native: "עברית", flag: "🇮🇱", rtl: true },
  { code: "hi", name: "Hindi", native: "हिन्दी", flag: "🇮🇳", rtl: false },
  { code: "hmn", name: "Hmong", native: "Hmong", flag: "🇨🇳", rtl: false },
  { code: "hu", name: "Hungarian", native: "Magyar", flag: "🇭🇺", rtl: false },
  { code: "is", name: "Icelandic", native: "Íslenska", flag: "🇮🇸", rtl: false },
  { code: "ig", name: "Igbo", native: "Igbo", flag: "🇳🇬", rtl: false },
  { code: "ilo", name: "Iloko", native: "Iloko", flag: "🇵🇭", rtl: false },
  { code: "id", name: "Indonesian", native: "Indonesia", flag: "🇮🇩", rtl: false },
  { code: "ga", name: "Irish", native: "Gaeilge", flag: "🇮🇪", rtl: false },
  { code: "it", name: "Italian", native: "Italiano", flag: "🇮🇹", rtl: false },
  { code: "ja", name: "Japanese", native: "日本語", flag: "🇯🇵", rtl: false },
  { code: "jv", name: "Javanese", native: "Jawa", flag: "🇮🇩", rtl: false },
  { code: "kn", name: "Kannada", native: "ಕನ್ನಡ", flag: "🇮🇳", rtl: false },
  { code: "kk", name: "Kazakh", native: "Қазақ тілі", flag: "🇰🇿", rtl: false },
  { code: "km", name: "Khmer", native: "ខ្មែរ", flag: "🇰🇭", rtl: false },
  { code: "rw", name: "Kinyarwanda", native: "Kinyarwanda", flag: "🇷🇼", rtl: false },
  { code: "ko", name: "Korean", native: "한국어", flag: "🇰🇷", rtl: false },
  { code: "ku", name: "Kurdish", native: "Kurdî (kurmancî)", flag: "🇮🇶", rtl: true },
  { code: "ky", name: "Kyrgyz", native: "Кыргызча", flag: "🇰🇬", rtl: false },
  { code: "lo", name: "Lao", native: "ລາວ", flag: "🇱🇦", rtl: false },
  { code: "la", name: "Latin", native: "Latin", flag: "🇻🇦", rtl: false },
  { code: "lv", name: "Latvian", native: "Latviešu", flag: "🇱🇻", rtl: false },
  { code: "ln", name: "Lingala", native: "Lingála", flag: "🇨🇩", rtl: false },
  { code: "lt", name: "Lithuanian", native: "Lietuvių", flag: "🇱🇹", rtl: false },
  { code: "lb", name: "Luxembourgish", native: "Lëtzebuergesch", flag: "🇱🇺", rtl: false },
  { code: "mk", name: "Macedonian", native: "Македонски", flag: "🇲🇰", rtl: false },
  { code: "mg", name: "Malagasy", native: "Malagasy", flag: "🇲🇬", rtl: false },
  { code: "ms", name: "Malay", native: "Melayu", flag: "🇲🇾", rtl: false },
  { code: "ml", name: "Malayalam", native: "മലയാളം", flag: "🇮🇳", rtl: false },
  { code: "mt", name: "Maltese", native: "Malti", flag: "🇲🇹", rtl: false },
  { code: "mi", name: "Māori", native: "Māori", flag: "🇳🇿", rtl: false },
  { code: "mr", name: "Marathi", native: "मराठी", flag: "🇮🇳", rtl: false },
  { code: "mn", name: "Mongolian", native: "Монгол", flag: "🇲🇳", rtl: false },
  { code: "ne", name: "Nepali", native: "नेपाली", flag: "🇳🇵", rtl: false },
  { code: "nb", name: "Norwegian Bokmål", native: "Norsk bokmål", flag: "🇳🇴", rtl: false },
  { code: "nn", name: "Norwegian Nynorsk", native: "Norsk nynorsk", flag: "🇳🇴", rtl: false },
  { code: "or", name: "Odia", native: "ଓଡ଼ିଆ", flag: "🇮🇳", rtl: false },
  { code: "om", name: "Oromo", native: "Oromoo", flag: "🇪🇹", rtl: false },
  { code: "ps", name: "Pashto", native: "پښتو", flag: "🇦🇫", rtl: true },
  { code: "fa", name: "Persian", native: "فارسی", flag: "🇮🇷", rtl: true },
  { code: "pl", name: "Polish", native: "Polski", flag: "🇵🇱", rtl: false },
  { code: "pt", name: "Portuguese", native: "Português", flag: "🇵🇹", rtl: false },
  { code: "pt-BR", name: "Brazilian Portuguese", native: "Português (Brasil)", flag: "🇧🇷", rtl: false },
  { code: "pa", name: "Punjabi", native: "ਪੰਜਾਬੀ", flag: "🇮🇳", rtl: false },
  { code: "qu", name: "Quechua", native: "Runasimi", flag: "🇵🇪", rtl: false },
  { code: "ro", name: "Romanian", native: "Română", flag: "🇷🇴", rtl: false },
  { code: "ru", name: "Russian", native: "Русский", flag: "🇷🇺", rtl: false },
  { code: "sm", name: "Samoan", native: "Samoan", flag: "🇼🇸", rtl: false },
  { code: "sa", name: "Sanskrit", native: "संस्कृत भाषा", flag: "🇮🇳", rtl: false },
  { code: "gd", name: "Scottish Gaelic", native: "Gàidhlig", flag: "🇬🇧", rtl: false },
  { code: "sr", name: "Serbian", native: "Српски", flag: "🇷🇸", rtl: false },
  { code: "st", name: "Southern Sotho", native: "Southern Sotho", flag: "🇱🇸", rtl: false },
  { code: "sn", name: "Shona", native: "ChiShona", flag: "🇿🇼", rtl: false },
  { code: "sd", name: "Sindhi", native: "سنڌي", flag: "🇵🇰", rtl: true },
  { code: "si", name: "Sinhala", native: "සිංහල", flag: "🇱🇰", rtl: false },
  { code: "sk", name: "Slovak", native: "Slovenčina", flag: "🇸🇰", rtl: false },
  { code: "sl", name: "Slovenian", native: "Slovenščina", flag: "🇸🇮", rtl: false },
  { code: "so", name: "Somali", native: "Soomaali", flag: "🇸🇴", rtl: false },
  { code: "es", name: "Spanish", native: "Español", flag: "🇪🇸", rtl: false },
  { code: "es-MX", name: "Mexican Spanish", native: "Español de México", flag: "🇲🇽", rtl: false },
  { code: "su", name: "Sundanese", native: "Basa Sunda", flag: "🇮🇩", rtl: false },
  { code: "sw", name: "Swahili", native: "Kiswahili", flag: "🇰🇪", rtl: false },
  { code: "sv", name: "Swedish", native: "Svenska", flag: "🇸🇪", rtl: false },
  { code: "tg", name: "Tajik", native: "Тоҷикӣ", flag: "🇹🇯", rtl: false },
  { code: "ta", name: "Tamil", native: "தமிழ்", flag: "🇮🇳", rtl: false },
  { code: "tt", name: "Tatar", native: "Татар", flag: "🇷🇺", rtl: false },
  { code: "te", name: "Telugu", native: "తెలుగు", flag: "🇮🇳", rtl: false },
  { code: "th", name: "Thai", native: "ไทย", flag: "🇹🇭", rtl: false },
  { code: "bo", name: "Tibetan", native: "བོད་སྐད་", flag: "🇨🇳", rtl: false },
  { code: "ti", name: "Tigrinya", native: "ትግርኛ", flag: "🇪🇷", rtl: false },
  { code: "ts", name: "Tsonga", native: "Tsonga", flag: "🇿🇦", rtl: false },
  { code: "tr", name: "Turkish", native: "Türkçe", flag: "🇹🇷", rtl: false },
  { code: "tk", name: "Turkmen", native: "Türkmen dili", flag: "🇹🇲", rtl: false },
  { code: "ak", name: "Akan", native: "Akan", flag: "🇬🇭", rtl: false },
  { code: "uk", name: "Ukrainian", native: "Українська", flag: "🇺🇦", rtl: false },
  { code: "ur", name: "Urdu", native: "اردو", flag: "🇵🇰", rtl: true },
  { code: "ug", name: "Uyghur", native: "ئۇيغۇرچە", flag: "🇨🇳", rtl: true },
  { code: "uz", name: "Uzbek", native: "O‘zbek", flag: "🇺🇿", rtl: false },
  { code: "vi", name: "Vietnamese", native: "Tiếng Việt", flag: "🇻🇳", rtl: false },
  { code: "cy", name: "Welsh", native: "Cymraeg", flag: "🇬🇧", rtl: false },
  { code: "wo", name: "Wolof", native: "Wolof", flag: "🇸🇳", rtl: false },
  { code: "xh", name: "Xhosa", native: "IsiXhosa", flag: "🇿🇦", rtl: false },
  { code: "yi", name: "Yiddish", native: "ייִדיש", flag: "🇮🇱", rtl: true },
  { code: "yo", name: "Yoruba", native: "Èdè Yorùbá", flag: "🇳🇬", rtl: false },
  { code: "zu", name: "Zulu", native: "IsiZulu", flag: "🇿🇦", rtl: false },
  { code: "ab", name: "Abkhazian", native: "Abkhazian", flag: "🇬🇪", rtl: false },
  { code: "ay", name: "Aymara", native: "Aymara", flag: "🇧🇴", rtl: false },
  { code: "bh", name: "Bhojpuri", native: "Bhojpuri", flag: "🇮🇳", rtl: false },
  { code: "br", name: "Breton", native: "Brezhoneg", flag: "🇫🇷", rtl: false },
  { code: "ch", name: "Chamorro", native: "Chamorro", flag: "🇬🇺", rtl: false },
  { code: "cv", name: "Chuvash", native: "Чӑваш", flag: "🇷🇺", rtl: false },
  { code: "dz", name: "Dzongkha", native: "རྫོང་ཁ", flag: "🇧🇹", rtl: false },
  { code: "fo", name: "Faroese", native: "Føroyskt", flag: "🇫🇴", rtl: false },
  { code: "fj", name: "Fijian", native: "Fijian", flag: "🇫🇯", rtl: false },
  { code: "ff", name: "Fula", native: "Pulaar", flag: "🇸🇳", rtl: false },
  { code: "gv", name: "Manx", native: "Gaelg", flag: "🇮🇲", rtl: false },
  { code: "iu", name: "Inuktitut", native: "Inuktitut", flag: "🇨🇦", rtl: false },
  { code: "kl", name: "Kalaallisut", native: "Kalaallisut", flag: "🇬🇱", rtl: false },
  { code: "ks", name: "Kashmiri", native: "کٲشُر", flag: "🇮🇳", rtl: false },
  { code: "kg", name: "Kongo", native: "Kongo", flag: "🇨🇩", rtl: false },
  { code: "ki", name: "Kikuyu", native: "Gikuyu", flag: "🇰🇪", rtl: false },
  { code: "lu", name: "Luba-Katanga", native: "Tshiluba", flag: "🇨🇩", rtl: false },
  { code: "mh", name: "Marshallese", native: "Marshallese", flag: "🇲🇭", rtl: false },
  { code: "na", name: "Nauru", native: "Nauru", flag: "🇳🇷", rtl: false },
  { code: "nv", name: "Navajo", native: "Navajo", flag: "🇺🇸", rtl: false },
  { code: "oc", name: "Occitan", native: "Occitan", flag: "🇫🇷", rtl: false },
  { code: "os", name: "Ossetic", native: "Ирон", flag: "🇬🇪", rtl: false },
  { code: "rm", name: "Romansh", native: "Rumantsch", flag: "🇨🇭", rtl: false },
  { code: "sc", name: "Sardinian", native: "Sardu", flag: "🇮🇹", rtl: false },
  { code: "se", name: "Northern Sami", native: "Davvisámegiella", flag: "🇳🇴", rtl: false },
  { code: "sg", name: "Sango", native: "Sängö", flag: "🇨🇫", rtl: false },
  { code: "ss", name: "Swati", native: "Swati", flag: "🇸🇿", rtl: false },
  { code: "tn", name: "Tswana", native: "Tswana", flag: "🇧🇼", rtl: false },
  { code: "to", name: "Tongan", native: "Lea fakatonga", flag: "🇹🇴", rtl: false },
  { code: "tw", name: "Twi", native: "Twi", flag: "🇬🇭", rtl: false },
  { code: "ty", name: "Tahitian", native: "Tahitian", flag: "🇵🇫", rtl: false },
  { code: "ve", name: "Venda", native: "Venda", flag: "🇿🇦", rtl: false },
  { code: "vo", name: "Volapük", native: "Volapük", flag: "🌐", rtl: false },
  { code: "wa", name: "Walloon", native: "Walloon", flag: "🇧🇪", rtl: false },
];

export const DEFAULT_LANGUAGE = LANGUAGES.find((l) => l.code === "en")!;

export function findLanguage(code: string): Language {
  return LANGUAGES.find((l) => l.code === code) ?? DEFAULT_LANGUAGE;
}

